<a href="https://www.kaggle.com/code/tiheli/one-hot-encoding-sklearn-with-churn-modelling?scriptVersionId=208820431" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/bank-customer-churn-prediction-dataset/Churn_Modelling.csv

In [2]:
# Load the dataset for customer churn prediction into a DataFrame
df=pd.read_csv('/kaggle/input/bank-customer-churn-prediction-dataset/Churn_Modelling.csv')

In [3]:
from sklearn.ensemble import RandomForestClassifier  # Import classifier for churn prediction
from sklearn.model_selection import train_test_split  # Import to split data into training and test sets

df.head(3)  # Display the first 3 rows of the dataset to check initial data structure if we use df.head() just show the first 3 rows of the dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [4]:
df = df.drop(columns=["RowNumber", "CustomerId", "Surname"])  # Remove unnecessary columns for prediction
df.head(3)  # Display the first 3 rows to confirm column removal

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [5]:
df = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True)  # Convert categorical columns to dummy variables

In [6]:
y = df["Exited"]  # Define target variable for prediction (whether customer exited)
x = df.drop("Exited", axis=1)  # Define feature set by dropping the target column & you can use x = df.drop(columns=['Exited'])

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=61,train_size=0.7) # Split data into training and test sets

In [8]:
rf = RandomForestClassifier()  # Initialize the random forest classifier
model = rf.fit(x_train, y_train)  # Train the model on the training set
model.score(x_test, y_test)  # Evaluate model accuracy on the test set

0.8623333333333333

In [9]:
model.predict([[712, 31, 9, 0, 5, 1, 1, 200000, False, False, True]])  # Predict customer churn for given features

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [10]:
model.predict([[450, 40, 7, 1, 3, 0, 1, 150000, True, False, False]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [11]:
from sklearn.preprocessing import OneHotEncoder  # Import the OneHotEncoder for encoding categorical variables

In [12]:
df = pd.read_csv('/kaggle/input/bank-customer-churn-prediction-dataset/Churn_Modelling.csv')  # Load the dataset into a DataFrame
df = df.drop(columns=["RowNumber", "CustomerId", "Surname"])  # Remove unnecessary columns for analysis

In [13]:
ohe = OneHotEncoder()  # Initialize the OneHotEncoder for converting categorical variables

In [14]:
encoded_features = ohe.fit_transform(df[['Geography', 'Gender']]).toarray()  # Apply one-hot encoding to the specified categorical columns

In [15]:
encoded_features

array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.]])

In [16]:
ohe.get_feature_names_out()  # Retrieve the names of the one-hot encoded features

array(['Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [17]:
encoded_features = pd.DataFrame(encoded_features)  # Convert the encoded features array into a DataFrame

In [18]:
encoded_features.columns = ohe.get_feature_names_out()  # Set the column names of the DataFrame to the encoded feature names

In [19]:
encoded_features

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,1.0,0.0
2,1.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...
9995,1.0,0.0,0.0,0.0,1.0
9996,1.0,0.0,0.0,0.0,1.0
9997,1.0,0.0,0.0,1.0,0.0
9998,0.0,1.0,0.0,0.0,1.0
9999,1.0,0.0,0.0,1.0,0.0

In [20]:
df.head(3)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [21]:
df=df.drop(columns=['Geography','Gender'])
df.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1

In [22]:
df[encoded_features.columns] = encoded_features  # Add the one-hot encoded features to the original DataFrame
df.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0,1.0,0.0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0,1.0,0.0
2,502,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0,1.0,0.0

In [23]:
y=df["Exited"]
x=df.drop("Exited",axis=1)

In [24]:
from sklearn.tree import DecisionTreeClassifier  # Import the DecisionTreeClassifier for classification tasks

In [25]:
tree = DecisionTreeClassifier()  # Initialize the Decision Tree classifier
model = tree.fit(x, y)  # Train the model on the feature set (x) and target variable (y)
model.score(x, y)  # Evaluate the model accuracy on the same data to check for overfitting
# overfitting

1.0

In [26]:
ohe.transform([["France", "Female"]]).toarray()  # Transform a new sample using the fitted OneHotEncoder

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0., 1., 0.]])